# Generated by Django 4.2.13 on 2024-05-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_result_value'),
        ('events', '0004_remove_athlete_organisation'),
    ]

    operations = [
    ]
