# Generated by Django 5.0.6 on 2024-05-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_athlete_organisation_alter_result_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='organisation',
        ),
    ]
